package de.upteams.tasktracker.user.util;

import de.upteams.tasktracker.user.dto.EmployeeDto;
import de.upteams.tasktracker.user.dto.response.UserCreateResponseDto;
import de.upteams.tasktracker.user.dto.response.UserResponseDto;
import de.upteams.tasktracker.user.entity.AppUser;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;

/**
 * Interface for Employee Mapping Service.
 * Implementation of that interface is generated by MapStruct framework.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING
)
public interface AppUserMapper {

    /**
     * Maps AppUser entity to UserResponseDto
     */
    @Mapping(target = "id", expression = "java(entity.getId() != null ? entity.getId().toString() : null)")
    @Mapping(target = "role", expression = "java(entity.getRole() != null ? entity.getRole().name() : null)")
    UserResponseDto mapEntityToDto(AppUser entity);

    /**
     * Maps AppUser entity to UserCreateResponseDto for registration responses
     */
    @Mapping(target = "id", expression = "java(entity.getId() != null ? entity.getId().toString() : null)")
    @Mapping(target = "role", expression = "java(entity.getRole() != null ? entity.getRole().name() : null)")
    @Mapping(target = "confirmationResent", constant = "false")
    UserCreateResponseDto mapEntityToCreateResponseDto(AppUser entity);

    /**
     * Maps AppUser entity to EmployeeDto for project assignments
     *
     */
//    @Mapping(target = "roles", expression = "java(java.util.List.of(entity.getRole().name()))")
//    @Mapping(target = "roles", ignore = true)  // Если поле roles не обязательна
    EmployeeDto mapToEmployeeDto(AppUser entity);
}
