package de.upteams.tasktracker.user.util;

import de.upteams.tasktracker.user.dto.EmployeeDto;
import de.upteams.tasktracker.user.dto.response.UserCreateResponseDto;
import de.upteams.tasktracker.user.dto.response.UserResponseDto;
import de.upteams.tasktracker.user.entity.AppUser;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;

/**
 * Interface for Employee Mapping Service.
 * Implementation of that interface is generated by MapStruct framework.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING
)
public interface AppUserMapper {

    @Mapping(target = "role", expression = "java(entity.getRole().name())")
    UserResponseDto mapEntityToDto(AppUser entity);

    @Mapping(target = "role", expression = "java(entity.getRole().name())")
    UserCreateResponseDto mapEntityToCreateResponseDto(AppUser entity);

    EmployeeDto mapToEmployeeDto(AppUser entity);
}
