$kind: http-example
request:
  url: "{{baseUrl}}/api/v1/tasks/:id"
  method: DELETE
  pathVariables:
    id: string
response:
  statusCode: 204
  statusText: No Content
  body:
    type: text
    content: ""
order: 1000
