$kind: http-example
request:
  url: "{{baseUrl}}/api/v1/tasks/:id"
  method: GET
  headers:
    Accept: application/json
  pathVariables:
    id: string
response:
  statusCode: 404
  statusText: Not Found
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "timestamp": "2025-04-26T10:00:00",
        "status": 404,
        "error": "Not Found",
        "message": "Task not found with id: 5",
        "path": "/api/v1/tasks/5"
      }
order: 2000
