$kind: http-request
description: Retrieves a task by its ID
url: http://{{baseUrl}}/api/v1/tasks/:id
method: GET
headers:
  Accept: application/json
pathVariables:
  id: string
body:
  type: text
  content: ""
examples: ./.resources/Get Task.resources/examples
order: 1000
