package de.upteams.tasktracker.project.utils;

import de.upteams.tasktracker.project.dto.request.ProjectCreateDto;
import de.upteams.tasktracker.project.dto.response.ProjectResponseDto;
import de.upteams.tasktracker.project.entity.Project;
import de.upteams.tasktracker.task.utils.TaskMappingService;
import de.upteams.tasktracker.user.util.AppUserMapper;
import org.mapstruct.*;

import java.util.List;

/**
 * Interface for Project Mapping Service.
 * Implementation of that interface is generated by MapStruct framework.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING,
        uses = {AppUserMapper.class, TaskMappingService.class}
)
public interface ProjectMapper {

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "owner", ignore = true)
    @Mapping(target = "tasks", ignore = true)
    @Mapping(target = "projectTeam", ignore = true)
    Project mapDtoToEntity(ProjectCreateDto dto);

    @Named("toResponseDto")
    @Mapping(target = "ownerId", source = "owner.id")
    ProjectResponseDto toResponseDto(Project project);

    @IterableMapping(qualifiedByName = "toResponseDto")
    List<ProjectResponseDto> toResponseDtoList(List<Project> projects);
}
